export const FETCHING_TRADING_PAIRS_DATA = 'FETCHING_TRADING_PAIRS_DATA';
export const FETCHING_TRADING_PAIRS_DATA_SUCCESS = 'FETCHING_TRADING_PAIRS_DATA_SUCCESS';
export const FETCHING_TRADING_PAIRS_FAIL = 'FETCHING_TRADING_PAIRS_FAIL';
